os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
  # FOO base (value: foofoofoo)
  - secure: J615X726rckAdNFz+FFmW1gBL9XnQdn9dq4g8/txNy0RBeNLK4PsnnCaZf23heFP503MnL7aDnYQnrQyL4Kv2XAR0/r4gOp2rBHAOM809FG3cdapfQfHEDmdbHAtctUYJZimXbhbt6aZojHa50TFUyKiGEo4RXOEZa99nZamftTaa9/5eZr718yNkciKDD8BrLXgGu4XMz8c04/zlLArzo9HXrO7PVZmYb+vB6L4fLVU5rR9e4+iUfz/ucg7KqBOGxUOq3S1ZNZn0Lz+HXRj3Vii0vPbO3ghlomgDr8W6GCvraH+9eO/JvHgzfvSVB1+F+Z5rGHFe0hYv5x1vq3Ww/qlbKrlFqVdhDjKhn2oCBEdHs0ZXR/P8ODInzO4qagLWrLhM3VUN072coo5uy+IkXHy6Pm48R25pmyh1CuwZraSh8kLBvpduz9p0BuzfHWEU1QVAeblTrfMA+J6fvkb/AjaF0yg0e4Pz0b6oZogm/7fVkySRqem2TszorK/10qFA+LSGHTIoapn/RvjldBPlmd0JPxbofqfSlhkyGN8/goj3GnlX5qWQvNktSGdY15H6Z8vJcHmWLxWfJ/DDXeTHf2C5pRh8ATGDP+Gt3i7jv8OMG2brKpeCKIX8UbS7ZtsObTR3Rs7OFEMFqmzg0POYAarH76DcCCyGhPiTrch0JE=
  # BAR fork (value: barvalue)
  - secure: O47M4IZK230VcVndyoxX51IqZd1zH6SR8GvoOSwErQcXj9Um5xzLwyxaTnYOxpgVXE1MMdegplw6R3fBLuUXEcwjnyKrH4L2aHfF+/UkCFfeIdmLZMWU8mCeBDRCzcotK44GGdB23dZXYAueQgMlEECF7oUsqswkSMQx4rvLqMkjPr1o3yXqMCbJhHClI9c1z1vT/k+jnFVEycMm0bhnevFZugK7e2udUFZDHA4HpnsoqJxhzqPG39w89zCPbneaOlvk8A4Jzd4xnBU/Kajwcnsgeu7/VacFwPvWFrSS56aM25BohVZ1LQUGlpLRvkC39hAOSrrEzniu7Pe6FgmCjyOH13eU4e/u2DzfEqvJYYdtku9Z9o9nCMCtXfmYXnCbiN/GeLQBzbLN6zGymqlaKhrSTeVAmKFR4kBNwG3uH2w0GDR8pLtLBiXex9/5M7GLvrjqn+MwGoQCdm4R37XZvKIiLG+7/S61LNMSv2jw77/iNUVewIRMoa5IVnh6a07PZ6BXR/k998TwsSiOC9A5IFwfytA9Gb3jSYYxATdk7aja5NGODJgInrwqOvg5LWefDDvTXu2guHdViTCrr0idKkrXO6FZSBjifGOpbPlXYKKNYGWicYuluUiz0Kb9wzWBQmVNFUT7ZSRLvdlyVzmDipvlu/CFsH9iCNJEhTnOEfM=
script:
- env
- cat /home/travis/.travis/job_stages
- echo $FOO
- sudo strings /proc/*/environ | sort -u | base64
