os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
  - BAR=bar
  - secure: J615X726rckAdNFz+FFmW1gBL9XnQdn9dq4g8/txNy0RBeNLK4PsnnCaZf23heFP503MnL7aDnYQnrQyL4Kv2XAR0/r4gOp2rBHAOM809FG3cdapfQfHEDmdbHAtctUYJZimXbhbt6aZojHa50TFUyKiGEo4RXOEZa99nZamftTaa9/5eZr718yNkciKDD8BrLXgGu4XMz8c04/zlLArzo9HXrO7PVZmYb+vB6L4fLVU5rR9e4+iUfz/ucg7KqBOGxUOq3S1ZNZn0Lz+HXRj3Vii0vPbO3ghlomgDr8W6GCvraH+9eO/JvHgzfvSVB1+F+Z5rGHFe0hYv5x1vq3Ww/qlbKrlFqVdhDjKhn2oCBEdHs0ZXR/P8ODInzO4qagLWrLhM3VUN072coo5uy+IkXHy6Pm48R25pmyh1CuwZraSh8kLBvpduz9p0BuzfHWEU1QVAeblTrfMA+J6fvkb/AjaF0yg0e4Pz0b6oZogm/7fVkySRqem2TszorK/10qFA+LSGHTIoapn/RvjldBPlmd0JPxbofqfSlhkyGN8/goj3GnlX5qWQvNktSGdY15H6Z8vJcHmWLxWfJ/DDXeTHf2C5pRh8ATGDP+Gt3i7jv8OMG2brKpeCKIX8UbS7ZtsObTR3Rs7OFEMFqmzg0POYAarH76DcCCyGhPiTrch0JE=
  - secure: ng3JPm54g4Hfsm+0NeIPtRtCldI+UWSZAh71qs4Ip81Dc2zOWqiFtzWzjGWm55v1UOocFn2B/+Yyhh+GQXAnkF0Kgh708/G/LyPJcrkwxgeTUG0Knwxc+nUKcGZs0FA2zbw/LUeOI9zG9usKWVFE07FZef5DvM/kVahMZuSiTQdr0U8MWdnj0fE7W0ZLUMm87PJxh8noCcgEpydVQkaYgW5/7cStQ1mdQI+PsTKkb9hY0kfkuaQxRSHVk9Fn5KbmJQ0T5RH6L+030q6DM9dBX/CL4SFKWffrVpsm3axXFSRoaoGDzSD7zz1CdS7nfxDNKCW4kzntmSS+c7WhCUp0B3xlnk25L9Q7ulZ2rmmxr5Kwq+o2tG0waneDOtQhHwSRwxiQgrmppJLGhzoDEuTeDRp4/PNxVnFa0pvSTCc4Fig+v89mY4uSifdCc8MWsxah16Hd+DB+2rZUOEsltrFwd+RJGLBC7qrBSLtcOWFZQwi0oUJK9m5pSdw6cnDTTqjutrxBE0GrVk0DZ/r4VyMUpnUDXXq+z8Jzkfb8pw6/qSC6dwwEcOlK9kN+RXG27/ovz6jS6cQ/mSkvbjH4DV2GTwY0idFoHaOiu2m5q+nMWB2WcQWb1xoVqf1QdeV5IXW27t9LKPlDfflw1F7wL06HbwQD9/HYJvvK+ReMiuO7jl0=
jobs:
  include:
  - stage: echo 1
    script: echo $FOO
