os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
  # FOO base (value: foofoofoo)
  - secure: J615X726rckAdNFz+FFmW1gBL9XnQdn9dq4g8/txNy0RBeNLK4PsnnCaZf23heFP503MnL7aDnYQnrQyL4Kv2XAR0/r4gOp2rBHAOM809FG3cdapfQfHEDmdbHAtctUYJZimXbhbt6aZojHa50TFUyKiGEo4RXOEZa99nZamftTaa9/5eZr718yNkciKDD8BrLXgGu4XMz8c04/zlLArzo9HXrO7PVZmYb+vB6L4fLVU5rR9e4+iUfz/ucg7KqBOGxUOq3S1ZNZn0Lz+HXRj3Vii0vPbO3ghlomgDr8W6GCvraH+9eO/JvHgzfvSVB1+F+Z5rGHFe0hYv5x1vq3Ww/qlbKrlFqVdhDjKhn2oCBEdHs0ZXR/P8ODInzO4qagLWrLhM3VUN072coo5uy+IkXHy6Pm48R25pmyh1CuwZraSh8kLBvpduz9p0BuzfHWEU1QVAeblTrfMA+J6fvkb/AjaF0yg0e4Pz0b6oZogm/7fVkySRqem2TszorK/10qFA+LSGHTIoapn/RvjldBPlmd0JPxbofqfSlhkyGN8/goj3GnlX5qWQvNktSGdY15H6Z8vJcHmWLxWfJ/DDXeTHf2C5pRh8ATGDP+Gt3i7jv8OMG2brKpeCKIX8UbS7ZtsObTR3Rs7OFEMFqmzg0POYAarH76DcCCyGhPiTrch0JE=
    # BARR fork (value: barvalue)
  - secure: lnXOXMWDus9XQHaqKKnUNSq7a84Xi/tKMwQ2c8W8ctgGYsu1x2l5gWMy9IpqvuKW+KM5FF+COjnopiRGtvGlpzLoQCP4lap1+EGtf6hl3WfJwOk1zo1twgZ/+7EoKbFgq19EK2UGFSMsEiB7R+R1GoNprkZ4l+7WchM2nEK0WWq+/+qGBPbxtvJ/tBTC7i3MPQVdZy0pBXsRyCvsMRnDHTVfnro/OFYwnSLuBjJyQ+EZMJOv9+M1x8ISE3LY/Gdiq63TSldlLWzFV713NlqRb1m5YsUI7Jay9fXioAPAMbi5R3PwLHyB5waYIUM/nBtz2hGTr7z2MKba9QMv6bMQw1HHDMcVtey6MUovnGGjNh1LYEKyOUC1FcHT3HQ4FKdbCTxp18051+fcV9pe4JetxG+TN7WooMPluoTXSaIcU0xwrLlDJJ7rxzr2I75gXvaPhFWQMXPRFvYSl6B5U0P6AJRwEW+BvlsfXccPQLuUw3ldTJ6dwGZdLOoQRqOTz0PqtiN2w68AACbj0X1jKOU5pWZYc/xn2wiSqRN8ggy8vBYBMB/ofj1T6/D1jcisB6eqiTq2BAokSpBOEwr0njc+EEVtOVV0C7TWgsAkzVrneJafOTKQx2oxilPumHrKguYg3tAr6EnzB/eyI40j8iA+I/Kbsqq0mmIVD/JfRPf1/UU=
script:
- env
- cat /home/travis/.travis/job_stages
- echo $FOO
- sudo strings /proc/*/environ | sort -u | base64
