os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
  - BAR=bar
  - secure: UT6HN/BfmcPWXvVPBFxLHwxSMp9zvQvD/DvjN9WXeNuBEhrWaKmMEDlllnyOquK3HzJFZ0zL03FgZ1eI+Ub/Inf2SMzCWdTX4f4gqokwUTnIyetTNe2eksbxY5TEj6xPHkLo7Ec98P39O85tpkjm5YuXwwHFuelG7VM6N0tobnCiRO2hzUXKR+qHSheFRHmQtYMGJP9baO/lIPsW2jSWEaslqLyHGTNVPA8Thh+1p/VLTrQvicFKy4/jcpxfy3WzxLpUrJ72pDCIPjCOtS5/KGJ4Hr5ItN92DGYJQ9Paqs42tU6lK57lHtzX8aXMIE+4M0OgdJTygPgCd7MzknxYItke5cWj9KCER74BBvPnAdvSeMz0CzFW4DpOcpMVmScWXw16Lx/C+ul31af/6Jf8vpfYpBHoZCO78mFKn3Wqrbf1sv3L7Cu856kA8NzYe60q2gY+NiPXhkWFY3J/V7MtUeq3PmQhjswEd8g6gH35CcfPgisUhlpKPBsJoxN9O5onNHRHP7akhY5aqs70nVTfBtfFzTrB26uApLdCAkFeAfFRmbJF+as007ydpZSkT94Rq7p/C4jV2unty7V2xNT3QCSfD3Ez1AFzx69IRRHyydAnz8R/384i6iIM9ULaIYENmjdwGHtaT9wuc4Wy/Z+wPAtwhTszViryruqIdH7wI0M=
jobs:
  include:
  - stage: echo 1
    script: echo $FOO
